### ISSUE TITLE
Patch to add strings for KmlDomType printing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [libkml/libkml#164]
```
Quick patch to kml22.h that generates an array of strings that correspond to 
the types in the KmlDomType enum. The global array, named KmlDomTypeString, can 
be used like this:

KmlDomType type;
type = feature->Type();
cout << KmlDomTypeString[type] << endl;

It was helpful for me, so I thought I would submit it. 

Thanks for making such a useful library!

Will
```

Original issue reported on code.google.com by `hawki...@gmail.com` on 8 Mar 2011 at 8:10

Attachments:
- [kml22.h.patch](https://storage.googleapis.com/google-code-attachments/libkml/issue-164/comment-0/kml22.h.patch)

**Comment by rashadkm** [comment]
should this be a function?
type_string = feature->TypeAsString();

**Comment by rashadkm** [comment]
fixed.

https://github.com/libkml/libkml/pull/230
