### ISSUE TITLE
minizip compile issue on linux

### ISSUE THREAD

**Issue by jmarca** [libkml/libkml#227]
I tried to compile this today and failed.

I did "mkdir build; cd build; cmake ..; make" and make failed trying to build MiniZip.

Poking around the source and the internet, I instead cloned MiniZip from https://github.com/rashadkm/minizip and built that.

It compiled fine, installed fine, and then libkml built and installed fine.

So maybe update the files on sourceforge for MiniZip?

**Comment by rashadkm** [comment]
file download from sourceforge is not used now. minizip sources if not found are simply git cloned in the current master branch.

Are you having issues with current master branch?

**Comment by jmarca** [comment]
I believe so, but I'm not 100% sure. I will double check later tonight.  As I said, I just tried to follow the build steps above using and it failed. It only worked if I separately built minizip. The build process downloaded from source forge, as I recall

**Comment by jmarca** [comment]
Okay now I am remembering.  Yes, minizip fails to compile on my system.  When I opened this issue, I had a situation where I was able to build minizip, as reported.  Then I kept trying to figure out what was going on and it kept failing and I gave up.

Closing this bug, opening one on minizip.

**Comment by jmarca** [comment]
I can't make an issue over on your clone of minizip.

fyi, when I run cmake on minizip, I get:

```
Scanning dependencies of target miniunz
[ 82%] Building C object CMakeFiles/miniunz.dir/miniunz.c.o
[ 88%] Linking C executable miniunz
libminizip.so.1.2.8: undefined reference to `get_crc_table'
libminizip.so.1.2.8: undefined reference to `inflate'
libminizip.so.1.2.8: undefined reference to `crc32'
libminizip.so.1.2.8: undefined reference to `deflate'
libminizip.so.1.2.8: undefined reference to `deflateInit2_'
libminizip.so.1.2.8: undefined reference to `inflateEnd'
libminizip.so.1.2.8: undefined reference to `deflateEnd'
libminizip.so.1.2.8: undefined reference to `inflateInit2_'
collect2: error: ld returned 1 exit status
CMakeFiles/miniunz.dir/build.make:95: recipe for target 'miniunz' failed
make[2]: *** [miniunz] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/miniunz.dir/all' failed
make[1]: *** [CMakeFiles/miniunz.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

On the other hand, if I do the standard

```
libtoolize
aclocal
autoconf
automake --add-missing
./configure
make
```

it builds fine.

My system is slackware 14.2 current (beta 1 I believe).  

But I decided that I don't really need libkml support in postgis...too much trouble to get this to compile cleanly on my platforms and no real need for it.

**Comment by rashadkm** [comment]
okay. This was error due to not linking with zlib. I had fixed this in the past. Will check if it reappeared again.

Thanks anyway for pointing this out.
