### ISSUE TITLE
LibKML and Gentoo Linux

### ISSUE THREAD

**Issue by imkoyodev** [libkml/libkml#240]
Hello.

I'm trying to install libkml but an error occurs during the compilation process. I attached the log compile, any suggestions to fix it?

[libkml_compile.txt](https://github.com/libkml/libkml/files/221881/libkml_compile.txt)

**Comment by rashadkm** [comment]
can you post the version of zlib you are using? 

or attach output of cmake configure..

**Comment by rashadkm** [comment]
no update from user. closing.

**Comment by pyongyang666** [comment]
Still seeing this issue. zlib version is zlib-1.2.11-r2
- CMAKE_BUILD_TYPE is not set. setting it to 'Release'
-- Boost version: 1.65.0
-- Found Boost: 106500
-- [SuperFind] EXPAT found from system
-- [SuperFind] ZLIB found from system
-- [SuperFind] MiniZip found from system
-- Could NOT find UriParser library
-- [SuperFind] UriParser found using config from /tmp/cmake-build/third-party/Build/UriParser
-- Configuring done
-- Generating done
-- Build files have been written to: /home/useraccount/libkml
